// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjirjfzocgidmubczgdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqaXJqZnpvY2dpZG11YmN6Z2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTMyMzUsImV4cCI6MjA3Mjk4OTIzNX0.arS-XRovGRdpfiI8Foaz0jD0uxV1c6X08YbmC3tfmHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});